### ISSUE TITLE
Connection error "Diffie-Hellman routines:DH_check_params_ex:modulus too small"

### ISSUE THREAD

**Issue by InyoEndo** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#44]
Have token, but getting this error when module attempts to connect:

[6/10/2023, 10:03:15 AM] [Air Conditioner] Connection closed because error occured
[6/10/2023, 10:03:15 AM] [Air Conditioner] Trying to reconnect in 5s...
[6/10/2023, 10:03:20 AM] [Air Conditioner] Connecting...
[6/10/2023, 10:03:21 AM] [Air Conditioner] Error occured: C027D9A3D27F0000:error:0280007E:Diffie-Hellman routines:DH_check_params_ex:modulus too small:../deps/openssl/openssl/crypto/dh/dh_check.c:40:

**Comment by InyoEndo** [comment]
OK, so was able to fix this buy duplicating the setting that allowed the Token process to work from here: https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/issues/43

From within air-conditioner-api.js, remove or comment out line 42. Replace the ciphers value at line 47 with 'HIGH:!DH:!aNULL'

AirConditionerApi.prototype = {
    connect: function () {
        this.log('Connecting...');

        this.controlCallbacks = {};

        const pfxPath = path.join(__dirname, '../res/cert.pfx')

        const options = {
            **// pfx: fs.readFileSync(pfxPath),**
            port: port,
            host: this.ipAddress,
            rejectUnauthorized: false,
            secureProtocol: 'TLSv1_method',
	    **ciphers: 'HIGH:!DH:!aNULL'**
            //ciphers: 'ALL:@SECLEVEL=0'
        };

**Comment by SebastianOsinski** [comment]
I just released version 3.1.0 which adds option for skipping certificate. Refer to README to see what arguments/config to pass to enable this.

**Comment by Swalabrr** [comment]
I'm getting this error also on an AR09HSSFAWKN. I've tried running homebridge-samsung-ac-get-token with and without --skipCertificate. The error changes, but still an error. 

![image](https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/assets/96663998/0de862d8-d26e-4439-b625-f77155e413c1)

**Comment by Swalabrr** [comment]
I'm also getting this DH error. I've tried with --skipCertificate, but i just get a different error. 

![image](https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/assets/96663998/a138f68a-8fca-4dae-9a4c-22c8fb199f46)

**Comment by Swalabrr** [comment]
> I'm also getting this DH error. I've tried with --skipCertificate, but i just get a different error.
> 
> ![image](https://user-images.githubusercontent.com/96663998/273666890-a138f68a-8fca-4dae-9a4c-22c8fb199f46.png)

Solved. I've tried using Ubuntu 22.04.3 LTS (no updates) and with this specific version the script runs fine. Hopefully it will help somebody, someday.
